FROM jupyter/scipy-notebook:hub-2.3.0
RUN set -ex \
   && pip install \
   'prefect==1.2.1' \
   'mlflow==1.26.1' \
   'seldon-core==1.12.0' \
   'dask==2021.7.0' \
   'dask-kubernetes==2021.3.1' \
   'scikit-learn==1.1.1' \
   'kubernetes' \
   'boto3'